export const APP_VERSION = 'v1.0.0'
export const APP_STAGE = 'production'
export const APP_RELEASE_NOTE = '正式公開版として、旅行先検索、旅先詳細、移動時間、AI旅行プランを提供しています。'
export const APP_DEPLOY_TARGET = 'Vercel'
export const APP_API_MODE = 'サーバー経由'
export const APP_BETA_SCOPE = '正式公開'
